version: "3"
services:
  pocketbase:
    build: ./quizeopath-backend
    ports:
      - "8050:80"
    restart: always
    environment:
      - BASE_URL=/api
    # healthcheck:
    #   test: curl --fail http://localhost/api/ping || exit 1
    #   interval: 30s
    #   retries: 5
    #   timeout: 10s