services:
  pocketbase:
    build: ./quizeopath-backend
    ports:
      - "8051:8051"
    restart: always
    environment:
      - BASE_URL=/api
    volumes:
      - "/etc/quizeopath/pb_data:/pb/pb_data"
    healthcheck:
      test: curl --fail http://localhost:8051/api/health || exit 1
      interval: 60s
      retries: 5
      timeout: 20s
